site_name: Theatre of the Mind

theme:
  name: cinder
  custom_dir: custom_theme

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: "1-4"
  - attr_list
  - tables

plugins:
  - search
  - awesome-nav
  - redirects:
      redirect_maps:
        index.md: design-doc.md
  - exclude:
      glob:
        - "private/**"     # ignore docs/private/**

extra_css:
  - extra.css
