---
name: Render all Markdown docs to HTML + TOC

on:
  push:
    branches: [main]
    paths:
      - '**.md'
      - '.github/workflows/render-docs.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Ensure docs dir & assets
        run: |
          mkdir -p docs
          # Provide minimal defaults if missing
          [ -f docs/_style.css ] || echo "body { font-family: sans-serif; margin:2rem auto; max-width:900px; }" > docs/_style.css
          [ -f docs/_header.html ] || echo "<header><nav><a href='./index.html'>Home</a> · <a href='./docs.html'>Docs</a></nav><hr></header><main>" > docs/_header.html
          [ -f docs/_footer.html ] || echo "</main><hr><footer><small>© $(date +%Y) Theatre of the Mind</small></footer>" > docs/_footer.html

      - name: Render README -> docs/index.html
        run: |
          pandoc README.md \
            --from=gfm --to=html5 --standalone \
            --section-divs \
            --toc --toc-depth=3 \
            --metadata title="Theatre of the Mind" \
            --variable=class:markdown-body \
            --include-before-body=docs/_header.html \
            --include-after-body=docs/_footer.html \
            --css _style.css \
            -o docs/index.html

      - name: Render docs/*.md -> docs/*.html
        run: |
          shopt -s nullglob
          for file in docs/*.md; do
            base="$(basename "$file" .md)"
            pandoc "$file" \
              --from=gfm --to=html5 --standalone \
              --section-divs \
              --toc --toc-depth=3 \
              --metadata title="$base — Theatre of the Mind" \
              --variable=class:markdown-body \
              --include-before-body=docs/_header.html \
              --include-after-body=docs/_footer.html \
              --css _style.css \
              -o "docs/$base.html"
          done

      - name: Build docs index
        run: |
          {
            echo "<h1>Documentation</h1><ul>"
            for file in $(ls -1 docs/*.md 2>/dev/null | sort); do
              base="$(basename "$file" .md)"
              title="$(grep -m1 -E '^# ' "$file" | sed 's/^# //')"
              [ -n "$title" ] || title="$base"
              echo "<li><a href='./$base.html'>$title</a></li>"
            done
            echo "</ul>"
          } > docs/_toc.html

          cat docs/_header.html docs/_toc.html docs/_footer.html > docs/docs.html

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: auto-render Markdown to static HTML + anchors + docs index'
          file_pattern: |
            docs/*.html
            docs/_toc.html
            docs/_style.css
            docs/_header.html
            docs/_footer.html
